crinkapp/crink_api

controllers/NewslettersController.js
models/NewslettersModel.js
routes/newsletters.js

Fixed _getAll_ emails newsletter request

Integration update newsletter

---

views/newsletter.handlebars

- Replaced **svg** images by **png** for Gmail issues
- Replaced **localhost** link by **prod** link

Fixed image issues by Gmail

---

controllers/NewslettersController.js
models/NewslettersModel.js
routes/newsletters.js
views/newsletter.handlebars

- Replace updating value of _ex-subscriber_ by deleting it
- Removed _activate_newsletter_ from the **Model**

Cleanned newsletter system

---

app.js
controllers/NewslettersController.js

Integration unsubscribe check

---

models/SettingModel.js
models/UsersModel.js
sequelize.js

- fix bug settings and usersModel
- TagsModel finish

tags model

---

.idea/workspace.xml
models/CommentModel.js

add comment model

---

.idea/workspace.xml
models/LikeUserModel.js

add LikeUserModel

---

controllers/NewslettersController.js
controllers/UsersController.js
routes/users.js
views/reset-password.handlebars

Added the request that sent **mail** to **reset user password**.

Add reset password request and added to route

---

models/PublicationTagModel.js
models/UserTagModel.js
sequelize.js

• Added UserTag Model
• Added PublicationTag Model

Tags relation

---

controllers/UsersController.js
routes/users.js

- Add request for reset user password

update user password is ok

---

app.js
controllers/UsersController.js
package-lock.json
package.json
token/verifyToken.js

Fixe cookies

---

routes/userTag.js

fix swagger bug

---

app.js
controllers/PublicationController.js
routes/publications.js
routes/userTag.js
sequelize.js

Publication controller

---

app.js
controllers/CommentController.js
routes/comment.js

Comment controller

---

controllers/LikeUserController.js
routes/likeUser.js

- GET allUserLikes
- GET allLikesByPublicationId

adding getAllUserLikes and getAllLikesByPublicationId

---

app.js
controllers/SubscriptionController.js
models/SignaledModel.js
models/SubscriptionModel.js
routes/subscription.js
sequelize.js

- GET all user subscriptions
- GET all user subscribers
- POST subscribe
- GET nb  user subscriptions
- GET nb user subscribers

Subscription controller

---

app.js
controllers/LikeUserController.js
controllers/PublicationController.js
controllers/PublicationTagController.js
controllers/UserTagController.js
routes/publicationTag.js
routes/publications.js

- Added Get tags name based on ids
- Clean up publication controller

Publication by tags

---

controllers/PublicationController.js
controllers/SubscriptionController.js
controllers/UsersController.js
routes/subscription.js

- Optimization overall
- Add subscribe features

Nb sub user

---

.gitignore
controllers/DiagnosticController.js
controllers/PublicationController.js
controllers/TagsController.js
models/DiagnosticModel.js
models/TagsModel.js
routes/diagnostic.js

When adding a diagnostic :
- add the **diagnostic id** in user table
- add the **tags** corresponding to the diagnostic's answers of the user

Diagnostic controller update

---

app.js
controllers/SearchController.js
controllers/TagsController.js
routes/search.js
routes/tags.js

Search engine

---

controllers/PublicationController.js
controllers/SearchController.js
routes/search.js

Fixe search publications by tags

Fixe search
